name: Example-iOS-RAC
configs:
  Dev: debug
  Stg: debug
  Test: debug
  Prd: release
configFiles:
  Dev: Configs/Dev.xcconfig
  Stg: Configs/Stg.xcconfig
  Test: Configs/Test.xcconfig
  Prd: Configs/Prd.xcconfig
options:
  groupSortPosition: top
attributes:
  ORGANIZATIONNAME: Kyohei Ito
schemes:
  Example-iOS-RAC:
    build:
      targets:
        Example-iOS-RAC: all
    run:
      config: Dev
    profile:
      config: Prd
    analyze:
      config: Dev
    archive:
      config: Prd

  Presentation:
    build:
      targets:
        Presentation: all
        PresentationTests:
          - test
    run:
      config: Dev
    test:
      config: Test
      gatherCoverageData: true
      targets:
        - PresentationTests

  Domain:
    build:
      targets:
        Domain: all
        DomainTests:
          - test
    run:
      config: Dev
    test:
      config: Test
      gatherCoverageData: true
      targets:
        - DomainTests

  Entity:
    build:
      targets:
        Entity: all
        EntityTests:
          - test
    run:
      config: Dev
    test:
      config: Test
      gatherCoverageData: true
      targets:
        - EntityTests

targets:
  Example-iOS-RAC:
    type: application
    platform: iOS
    configFiles:
      Dev: Example-iOS-RAC/Configs/Dev.xcconfig
      Stg: Example-iOS-RAC/Configs/Stg.xcconfig
      Test: Example-iOS-RAC/Configs/Test.xcconfig
      Prd: Example-iOS-RAC/Configs/Prd.xcconfig
    sources:
      - Configs
      - Example-iOS-RAC
    dependencies:
      - target: Component
      - target: Domain
      - target: Entity
      - target: Presentation
      - target: UseCase
      - carthage: Plan
      - carthage: ReactiveCocoa
      - carthage: ReactiveSwift
    settings:
      base:
        CODE_SIGN_IDENTITY: $(inherited)

  Presentation:
    type: framework
    platform: iOS
    sources:
      - path: Presentation
    dependencies:
      - target: Component
      - target: Entity
      - target: UseCase
      - carthage: Plan
      - carthage: ReactiveSwift

  PresentationTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PresentationTests
    dependencies:
      - target: Presentation

  Domain:
    type: framework
    platform: iOS
    sources:
      - path: Domain
    dependencies:
      - target: Entity
      - target: UseCase
      - carthage: Plan
      - carthage: ReactiveSwift

  DomainTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - DomainTests
    dependencies:
      - target: Domain

  Component:
    type: framework
    platform: iOS
    sources:
      - path: Component
    dependencies:
      - target: Entity
      - target: UseCase
      - carthage: ReactiveCocoa
      - carthage: ReactiveSwift
      - carthage: Carbon
      - carthage: DifferenceKit

  UseCase:
    type: framework
    platform: iOS
    sources:
      - path: UseCase
    dependencies:
      - target: Entity
      - carthage: ReactiveSwift

  Entity:
    type: framework
    platform: iOS
    sources:
      - Entity

  EntityTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - EntityTests
    dependencies:
      - target: Entity
