name: Example-iOS-Rx
configs:
  Dev: debug
  Stg: debug
  Test: debug
  Prd: release
configFiles:
  Dev: Configs/Dev.xcconfig
  Stg: Configs/Stg.xcconfig
  Test: Configs/Test.xcconfig
  Prd: Configs/Prd.xcconfig
options:
  groupSortPosition: top
attributes:
  ORGANIZATIONNAME: Kyohei Ito
schemes:
  Example-iOS-Rx:
    build:
      targets:
        Example-iOS-Rx: all
    run:
      config: Dev
    profile:
      config: Prd
    analyze:
      config: Dev
    archive:
      config: Prd

  Catalog:
    build:
      targets:
        Catalog: all
    run:
      config: Dev
      environmentVariables:
        SNAPSHOT_DIR: $(SOURCE_ROOT)/Snapshots
    test:
      config: Test
      targets:
        - CatalogSnapshot
    profile:
      config: Prd
    analyze:
      config: Dev
    archive:
      config: Prd

  Presentation:
    build:
      targets:
        Presentation: all
        PresentationTests:
          - test
    run:
      config: Dev
    test:
      config: Test
      gatherCoverageData: true
      targets:
        - PresentationTests

  Gateway:
    build:
      targets:
        Gateway: all
        GatewayTests:
          - test
    run:
      config: Dev
    test:
      config: Test
      gatherCoverageData: true
      targets:
        - GatewayTests

  UseCase:
    build:
      targets:
        UseCase: all
        UseCaseTests:
          - test
    run:
      config: Dev
    test:
      config: Test
      gatherCoverageData: true
      targets:
        - UseCaseTests

  Entity:
    build:
      targets:
        Entity: all
        EntityTests:
          - test
    run:
      config: Dev
    test:
      config: Test
      gatherCoverageData: true
      targets:
        - EntityTests

targets:
  Example-iOS-Rx:
    type: application
    platform: iOS
    configFiles:
      Dev: Example-iOS-Rx/Configs/Dev.xcconfig
      Stg: Example-iOS-Rx/Configs/Stg.xcconfig
      Test: Example-iOS-Rx/Configs/Test.xcconfig
      Prd: Example-iOS-Rx/Configs/Prd.xcconfig
    sources:
      - Configs
      - Example-iOS-Rx
    dependencies:
      - target: Boundary
      - target: Component
      - target: Entity
      - target: Gateway
      - target: Presentation
      - target: UseCase
      - carthage: Plan
      - carthage: RxSwift

  Catalog:
    type: application
    platform: iOS
    configFiles:
      Dev: Catalog/Configs/Dev.xcconfig
      Stg: Catalog/Configs/Stg.xcconfig
      Test: Catalog/Configs/Test.xcconfig
      Prd: Catalog/Configs/Prd.xcconfig
    sources:
      - Configs
      - Catalog
    dependencies:
      - target: Boundary
      - target: Component
      - target: Entity
      - carthage: PlaybookUI
      - carthage: Playbook
      - carthage: RxRelay
      - carthage: RxCocoa
      - carthage: RxSwift
      - carthage: Carbon
      - carthage: DifferenceKit

  CatalogSnapshot:
    type: bundle.unit-test
    platform: iOS
    sources:
      - CatalogSnapshot
    dependencies:
      - target: Catalog
      - carthage: PlaybookSnapshot

  Presentation:
    type: framework
    platform: iOS
    sources:
      - path: Presentation
    dependencies:
      - target: Boundary
      - target: Component
      - target: Entity
      - carthage: Plan
      - carthage: RxSwift
      - carthage: RxRelay

  PresentationTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PresentationTests
    dependencies:
      - target: Presentation

  Gateway:
    type: framework
    platform: iOS
    sources:
      - path: Gateway
    dependencies:
      - target: Entity
      - target: UseCase
      - carthage: RxSwift

  GatewayTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - GatewayTests
    dependencies:
      - target: Gateway

  Component:
    type: framework
    platform: iOS
    sources:
      - path: Component
    dependencies:
      - target: Entity
      - target: Boundary
      - carthage: RxCocoa
      - carthage: RxSwift
      - carthage: Carbon
      - carthage: DifferenceKit

  UseCase:
    type: framework
    platform: iOS
    sources:
      - path: UseCase
    dependencies:
      - target: Boundary
      - target: Entity
      - carthage: RxSwift

  UseCaseTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - UseCaseTests
    dependencies:
      - target: UseCase

  Boundary:
    type: framework
    platform: iOS
    sources:
      - path: Boundary
    dependencies:
      - target: Entity

  Entity:
    type: framework
    platform: iOS
    sources:
      - Entity

  EntityTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - EntityTests
    dependencies:
      - target: Entity
