@startuml Plan Example Structure

title Plan Example Structure

file Example
note right : Example App

file Catalog
note right : UITest App

frame Presentation <<Framework>> {
  [Presenter]
  [Component] <<Framework>>
}

frame Gateway <<Framework>> {
  [Repository]
}

frame UseCase <<Framework>> {
  [Interactor]
  [Repository<I>]
  [Boundary<I>] <<Framework>>
}

frame Domain {
  [Entity] <<Framework>>
}

Example --> Presentation
Example --> Gateway
Example ---> UseCase
Gateway --> UseCase

Example --> Component
Catalog --> Component
Presenter -> Component

Interactor .> [Boundary<I>]
Presenter --> [Boundary<I>]
Component --> [Boundary<I>]

Repository ..> [Repository<I>]
Interactor --> [Repository<I>]

Component --> Entity
[Repository<I>] --> Entity
[Boundary<I>] -> Entity

@enduml