# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests using 'fastlane scan'"
  lane :run_project_tests do |options|
    scan(
      clean: true,
      scheme: "Plan",
      device: "iPhone 11 Pro",
      skip_slack: true,
      buildlog_path: "./build/tests_log"
    )
  end
end
